### ISSUE TITLE
[meta] Tracking issue for r0.6.1 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#184]
*Based on [the changelog on matrix-doc](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r061)*

# New Endpoints

- [ ] Add `/rooms/{roomId}/aliases` for retrieving local aliases for a room. ([#2562](https://github.com/matrix-org/matrix-doc/issues/2562))

# Backwards Compatible Changes

- [ ] Add data structures for defining moderation policies in rooms per [MSC2313](https://github.com/matrix-org/matrix-doc/pull/2313). ([#2434](https://github.com/matrix-org/matrix-doc/issues/2434))
- [ ] Optionally invalidate other access tokens during password modification per [MSC2457](https://github.com/matrix-org/matrix-doc/pull/2457). ([#2523](https://github.com/matrix-org/matrix-doc/issues/2523))
- [ ] Add User-Interactive Authentication for SSO-backed homeserver per [MSC2454](https://github.com/matrix-org/matrix-doc/pull/2454). ([#2532](https://github.com/matrix-org/matrix-doc/issues/2532))
- [ ] Add soft-logout support per [MSC1466](https://github.com/matrix-org/matrix-doc/issues/1466). ([#2546](https://github.com/matrix-org/matrix-doc/issues/2546))
- [ ] Replaced legacy room alias handling with a more sustainable solution per [MSC2432](https://github.com/matrix-org/matrix-doc/pull/2432). ([#2562](https://github.com/matrix-org/matrix-doc/issues/2562))

# Spec Clarifications

- [ ] List available enum values for the room versions capability. ([#2245](https://github.com/matrix-org/matrix-doc/issues/2245))
- [ ] Fix various spelling errors throughout the specification. ([#2351](https://github.com/matrix-org/matrix-doc/issues/2351), [#2415](https://github.com/matrix-org/matrix-doc/issues/2415), [#2453](https://github.com/matrix-org/matrix-doc/issues/2453), [#2524](https://github.com/matrix-org/matrix-doc/issues/2524), [#2553](https://github.com/matrix-org/matrix-doc/issues/2553), [#2569](https://github.com/matrix-org/matrix-doc/issues/2569))
- [ ] Minor clarifications to token-based User-Interactive Authentication. ([#2369](https://github.com/matrix-org/matrix-doc/issues/2369))
- [ ] Minor clarification for what the user directory searches. ([#2381](https://github.com/matrix-org/matrix-doc/issues/2381))
- [ ] Fix key export format example to match the specification. ([#2430](https://github.com/matrix-org/matrix-doc/issues/2430))
- [ ] Clarify the IV data type for encrypted files. ([#2492](https://github.com/matrix-org/matrix-doc/issues/2492))
- [ ] Fix the `.m.rule.contains_user_name` default push rule to set the highlight tweak. ([#2519](https://github.com/matrix-org/matrix-doc/issues/2519))
- [ ] Clarify that an `event_id` is returned when sending events. ([#2525](https://github.com/matrix-org/matrix-doc/issues/2525))
- [ ] Fix some numbers in the specification to match their explanation text. ([#2554](https://github.com/matrix-org/matrix-doc/issues/2554))
- [ ] Move redaction algorithm into the room version specifications. ([#2563](https://github.com/matrix-org/matrix-doc/issues/2563))
- [ ] Clarify signature object structures for encryption. ([#2566](https://github.com/matrix-org/matrix-doc/issues/2566))
- [ ] Clarify which events are created as part of `/createRoom`. ([#2571](https://github.com/matrix-org/matrix-doc/issues/2571))
- [ ] Remove claims that the homeserver is exclusively responsible for profile information in membership events. ([#2574](https://github.com/matrix-org/matrix-doc/issues/2574))
