### ISSUE TITLE
[meta] Tracking issue for r0.4.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#49]
*Based on [the changelog for r0.4.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r040). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

New Endpoints
-------------

- [x] `POST /user_directory/search` (<https://github.com/matrix-org/matrix-doc/issues/1096>)
- [x] `GET /rooms/{roomId}/event/{eventId}` (<https://github.com/matrix-org/matrix-doc/issues/1110>)
- [x] `POST /delete_devices` (<https://github.com/matrix-org/matrix-doc/issues/1239>)
- [x] `GET /thirdparty/*` Endpoints (<https://github.com/matrix-org/matrix-doc/issues/1353>)
- [x] `POST /account/3pid/msisdn/requestToken`, `POST /register/msisdn/requestToken`, and `POST /account/password/msisdn/requestToken` (<https://github.com/matrix-org/matrix-doc/issues/1507>)
- [x] `POST /account/3pid/delete` (<https://github.com/matrix-org/matrix-doc/issues/1567>)
- [x] `POST /rooms/{roomId}/read_markers` (<https://github.com/matrix-org/matrix-doc/issues/1635>)

Backwards Compatible Changes
----------------------------

- [x] Add more presence options to the `set_presence` parameter of `/sync`.a (<https://github.com/matrix-org/matrix-doc/issues/780>)
- [x] Add `token` parameter to the `/keys/query` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1104>)
- [x] Add the room visibility options for the room directory (<https://github.com/matrix-org/matrix-doc/issues/1141>)
- [x] Add spec for ignoring users (<https://github.com/matrix-org/matrix-doc/issues/1142>)
- [x] Add the `/register/available` endpoint for username availability (<https://github.com/matrix-org/matrix-doc/issues/1151>)
- [x] Add sticker messages (<https://github.com/matrix-org/matrix-doc/issues/1158>)
- [x] Specify how to control the power level required for `@room` (<https://github.com/matrix-org/matrix-doc/issues/1176>)
- [x] Document `/logout/all` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1263>)
- [x] Add report content API (<https://github.com/matrix-org/matrix-doc/issues/1264>)
- [x] Add `allow_remote` to the content repo to avoid routing loops (<https://github.com/matrix-org/matrix-doc/issues/1265>)
- [x] Document highlights field in /search response (<https://github.com/matrix-org/matrix-doc/issues/1274>)
- [x] End-to-end encryption for group chats:

  * Olm and Megolm messaging algorithms.
  * `m.room.encrypted`, `m.room.encryption`, `m.room_key` events.
  * Device verification process.
  * `device_one_time_keys_count` sync parameter.
  * `device_lists:left` sync parameter. (<https://github.com/matrix-org/matrix-doc/issues/1284>)
- [x] Add `.well-known` server discovery method (<https://github.com/matrix-org/matrix-doc/issues/1359>)
- [x] Document the GET version of `/login` (<https://github.com/matrix-org/matrix-doc/issues/1361>)
- [x] Document the `server_name` parameter on `/join/{roomIdOrAlias}` (<https://github.com/matrix-org/matrix-doc/issues/1364>)
- [x] Document the CORS/preflight headers (<https://github.com/matrix-org/matrix-doc/issues/1365>)
- [x] Add new user identifier object for logging in (<https://github.com/matrix-org/matrix-doc/issues/1390>): https://github.com/ruma/ruma-client-api/pull/40
- [x] Document message formats on `m.text` and `m.emote` messages (<https://github.com/matrix-org/matrix-doc/issues/1397>)
- [x] Encrypt file attachments (<https://github.com/matrix-org/matrix-doc/issues/1420>)
- [x] Share room decryption keys between devices (<https://github.com/matrix-org/matrix-doc/issues/1465>)
- [x] Document and improve client interaction with pushers. (<https://github.com/matrix-org/matrix-doc/issues/1506>)
- [x] Add support for Room Versions. (<https://github.com/matrix-org/matrix-doc/issues/1516>): https://github.com/ruma/ruma-identifiers/issues/9
- [x] Guests can now call /context and /event to fetch events (<https://github.com/matrix-org/matrix-doc/issues/1542>)
- [x] Add a common standard for user, room, and group mentions in messages. (<https://github.com/matrix-org/matrix-doc/issues/1547>)
- [x] Add server ACLs as an option for controlling federation in a room. (<https://github.com/matrix-org/matrix-doc/issues/1550>)
- [x] Add new push rules for encrypted events and `@room` notifications. (<https://github.com/matrix-org/matrix-doc/issues/1551>)
- [x] Add third party network room directories, as provided by application services. (<https://github.com/matrix-org/matrix-doc/issues/1554>)
- [x] Document the `validated_at` and `added_at` fields on `GET /acount/3pid`. (<https://github.com/matrix-org/matrix-doc/issues/1567>)
- [x] Add an `inhibit_login` registration option. (<https://github.com/matrix-org/matrix-doc/issues/1589>)
- [x] Recommend that servers set a Content Security Policy for the content repository. (<https://github.com/matrix-org/matrix-doc/issues/1600>)
- [x] Add "rich replies" - a way for users to better represent the conversation thread they are referencing in their messages. (<https://github.com/matrix-org/matrix-doc/issues/1617>)
- [x] Add support for read markers. (<https://github.com/matrix-org/matrix-doc/issues/1635>)

Spec Clarifications
-------------------

- [x] Mark `home_server` return field for `/login` and `/register` endpoints as deprecated (<https://github.com/matrix-org/matrix-doc/issues/1097>): https://github.com/ruma/ruma-client-api/pull/40
- [x] Fix response format of `/keys/changes` endpoint (<https://github.com/matrix-org/matrix-doc/issues/1106>)
- [x] Clarify default values for some fields on the `/search` API (<https://github.com/matrix-org/matrix-doc/issues/1109>)
- [x] Fix the representation of `m.presence` events (<https://github.com/matrix-org/matrix-doc/issues/1137>)
- [x] Clarify that `m.tag` ordering is done with numbers, not strings (<https://github.com/matrix-org/matrix-doc/issues/1139>)
- [x] Clarify that `/account/whoami` should consider application services (<https://github.com/matrix-org/matrix-doc/issues/1152>)
- [x] Update `ImageInfo` and `ThumbnailInfo` dimension schema descriptions to clarify that they relate to intended display size, as opposed to the intrinsic size of the image file. (<https://github.com/matrix-org/matrix-doc/issues/1158>)
- [x] Mark `GET /rooms/{roomId}/members` as requiring authentication (<https://github.com/matrix-org/matrix-doc/issues/1245>)
- [x] Clarify `changed` field behaviour in device tracking process (<https://github.com/matrix-org/matrix-doc/issues/1284>)
- [x] Describe `StateEvent` for `/createRoom` (<https://github.com/matrix-org/matrix-doc/issues/1329>)
- [x] Describe how the `reason` is handled for kicks/bans (<https://github.com/matrix-org/matrix-doc/issues/1362>)
- [x] Mark `GET /presence/{userId}/status` as requiring authentication (<https://github.com/matrix-org/matrix-doc/issues/1371>)
- [x] Describe the rate limit error response schema (<https://github.com/matrix-org/matrix-doc/issues/1373>)
- [x] Clarify that clients must leave rooms before forgetting them (<https://github.com/matrix-org/matrix-doc/issues/1378>)
- [x] Document guest access in `/createRoom` presets (<https://github.com/matrix-org/matrix-doc/issues/1379>)
- [x] Define what a `RoomEvent` is on `/rooms/{roomId}/messages` (<https://github.com/matrix-org/matrix-doc/issues/1380>)
- [x] Clarify the request and result types on `/search` (<https://github.com/matrix-org/matrix-doc/issues/1381>)
- [x] Clarify some of the properties on the search result (<https://github.com/matrix-org/matrix-doc/issues/1400>)
- [x] Clarify how access tokens are meant to be supplied to the homeserver. (<https://github.com/matrix-org/matrix-doc/issues/1517>)
- [x] Document additional parameters on the `/createRoom` API. (<https://github.com/matrix-org/matrix-doc/issues/1518>)
- [x] Clarify that new push rules should be enabled by default, and that unrecognised conditions should not match. (<https://github.com/matrix-org/matrix-doc/issues/1551>)
- [x] Update all event examples to be accurate representations of their associated events. (<https://github.com/matrix-org/matrix-doc/issues/1558>)
- [x] Clarify the supported HTML features for room messages. (<https://github.com/matrix-org/matrix-doc/issues/1562>)
- [x] Move the `invite_room_state` definition under `unsigned` where it actually resides. (<https://github.com/matrix-org/matrix-doc/issues/1568>)
- [x] Clarify the homeserver's behaviour for searching users. (<https://github.com/matrix-org/matrix-doc/issues/1569>)
- [x] Clarify the object structures and defaults for Filters. (<https://github.com/matrix-org/matrix-doc/issues/1570>)
- [x] Clarify instances of `type: number` in the swagger/OpenAPI schema definitions. (<https://github.com/matrix-org/matrix-doc/issues/1571>)
- [x] Clarify that left rooms also have account data in `/sync`. (<https://github.com/matrix-org/matrix-doc/issues/1572>)
- [x] Clarify the event fields used in the `/sync` response. (<https://github.com/matrix-org/matrix-doc/issues/1573>)
- [x] Fix naming of the body field in `PUT /directory/room`. (<https://github.com/matrix-org/matrix-doc/issues/1574>)
- [x] Clarify the filter object schema used in room searching. (<https://github.com/matrix-org/matrix-doc/issues/1577>)
- [x] Document the 403 error for sending state events. (<https://github.com/matrix-org/matrix-doc/issues/1590>)
- [x] specify how to handle multiple olm sessions with the same device (<https://github.com/matrix-org/matrix-doc/issues/1596>)
- [x] Add the other keys that redactions are expected to preserve. (<https://github.com/matrix-org/matrix-doc/issues/1602>)
- [x] Clarify that clients should not be generating invalid HTML for formatted events. (<https://github.com/matrix-org/matrix-doc/issues/1605>)
- [x] Clarify the room tag structure (<https://github.com/matrix-org/matrix-doc/issues/1606>)
- [x] Add a note that clients may use the transaction ID to avoid flickering when doing local echo. (<https://github.com/matrix-org/matrix-doc/issues/1619>)
- [x] Include the request and response structures for the various `/requestToken` endpoints. (<https://github.com/matrix-org/matrix-doc/issues/1636>)
- [x] Clarify the available error codes, and when to prefer the HTTP status code over the `errcode`. (<https://github.com/matrix-org/matrix-doc/issues/1637>)
- [x] Clarify and generalise the language used for describing pagination. (<https://github.com/matrix-org/matrix-doc/issues/1642>)

**Comment by Nauxuron** [comment]
These endpoints are done:
- `POST /user_directory/search` (#46)
- `GET /thirdparty/*` (#44)

**Comment by iinuwa** [comment]
Done!
