### ISSUE TITLE
[meta] Tracking issue for r0.5.0 compatibility

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#50]
*Based on [the changelog for r0.5.0](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst#r050). ToDo: Add new endpoints, implement upstream changes, review spec clarifications.*

Breaking Changes
----------------

- [x] Add a new `submit_url` field to the responses of `/requestToken` which older clients will not be able to handle correctly. (<https://github.com/matrix-org/matrix-doc/issues/2101>)

Deprecations
------------

- [x] Remove references to presence lists. (<https://github.com/matrix-org/matrix-doc/issues/1817>)

New Endpoints
-------------

- [x] `GET /account_data` routes. (<https://github.com/matrix-org/matrix-doc/issues/1873>)

Backwards Compatible Changes
----------------------------

- [x] Add megolm session export format. (<https://github.com/matrix-org/matrix-doc/issues/1701>)
- [x] Add support for advertising experimental features to clients. (<https://github.com/matrix-org/matrix-doc/issues/1786>)
- [x] Add a generic SSO login API. (<https://github.com/matrix-org/matrix-doc/issues/1789>)
- [x] Add a mechanism for servers to redirect clients to an alternative homeserver after logging in. (<https://github.com/matrix-org/matrix-doc/issues/1790>)
- [x] Add room version upgrades. (<https://github.com/matrix-org/matrix-doc/issues/1791>, <https://github.com/matrix-org/matrix-doc/issues/1875>)
- [x] Support optional features by having clients query for capabilities. (<https://github.com/matrix-org/matrix-doc/issues/1829>, <https://github.com/matrix-org/matrix-doc/issues/1879>)
- [x] Add `M_RESOURCE_LIMIT_EXCEEDED` as an error code for when homeservers exceed limits imposed on them. (<https://github.com/matrix-org/matrix-doc/issues/1874>)
- [x] Emit `M_UNSUPPORTED_ROOM_VERSION` error codes where applicable on `/createRoom` and `/invite` APIs. (<https://github.com/matrix-org/matrix-doc/issues/1908>)
- [x] Add a `.m.rule.tombstone` default push rule for room ugprade notifications. (<https://github.com/matrix-org/matrix-doc/issues/2020>)
- [x] Add support for sending server notices to clients. (<https://github.com/matrix-org/matrix-doc/issues/2026>)
- [x] Add MSISDN (phone number) support to User-Interactive Authentication. (<https://github.com/matrix-org/matrix-doc/issues/2030>)
- [x] Add the option to lazy-load room members for increased client performance. (<https://github.com/matrix-org/matrix-doc/issues/2035>)
- [x] Add `id_server` to `/deactivate` and `/3pid/delete` endpoints to unbind from a specific identity server. (<https://github.com/matrix-org/matrix-doc/issues/2046>)
- [x] Add support for Olm sessions becoming un-stuck. (<https://github.com/matrix-org/matrix-doc/issues/2059>)
- [x] Add interactive device verification, including a common framework for device verification. (<https://github.com/matrix-org/matrix-doc/issues/2072>)

Spec Clarifications
-------------------

- [x] Change examples to use example.org instead of a real domain. (<https://github.com/matrix-org/matrix-doc/issues/1650>)
- [x] Clarify that `state_default` in `m.room.power_levels` always defaults to 50. (<https://github.com/matrix-org/matrix-doc/issues/1656>)
- [x] Add missing `status_msg` to `m.presence` schema. (<https://github.com/matrix-org/matrix-doc/issues/1744>)
- [x] Add the missing `m.push_rules` event schema. (<https://github.com/matrix-org/matrix-doc/issues/1889>)
- [x] Clarify how modern day local echo is meant to be solved by clients. (<https://github.com/matrix-org/matrix-doc/issues/1891>)
- [x] Clarify that `width` and `height` are required parameters on `/_matrix/media/r0/thumbnail/{serverName}/{mediaId}`. (<https://github.com/matrix-org/matrix-doc/issues/1975>): https://github.com/ruma/ruma-client-api/commit/6026d960ce7387dab7363e77f0980a02859e8fd9
- [x] Clarify how `m.login.dummy` can be used to disambiguate login flows. (<https://github.com/matrix-org/matrix-doc/issues/1999>)
- [x] Remove `prev_content` from the redaction algorithm's essential keys list. (<https://github.com/matrix-org/matrix-doc/issues/2016>)
- [x] Fix the `third_party_signed` definitions for the join APIs. (<https://github.com/matrix-org/matrix-doc/issues/2025>)
- [x] Clarify why User Interactive Auth is used on password changes and how access tokens are handled. (<https://github.com/matrix-org/matrix-doc/issues/2027>)
- [x] Clarify that devices are deleted upon logout. (<https://github.com/matrix-org/matrix-doc/issues/2028>)
- [x] Add `M_NOT_FOUND` error definition for deleting room aliases. (<https://github.com/matrix-org/matrix-doc/issues/2029>)
- [x] Add missing `reason` to `m.call.hangup`. (<https://github.com/matrix-org/matrix-doc/issues/2031>)
- [x] Clarify how redactions affect room state. (<https://github.com/matrix-org/matrix-doc/issues/2032>)
- [x] Clarify that `FAIL_ERROR` in autodiscovery is not limited to just homeservers. (<https://github.com/matrix-org/matrix-doc/issues/2036>)
- [x] Fix example `Content-Type` for `/media/upload` request. (<https://github.com/matrix-org/matrix-doc/issues/2041>)
- [x] Clarify that login flows are meant to be completed in order. (<https://github.com/matrix-org/matrix-doc/issues/2042>)
- [x] Clarify that clients should not send read receipts for their own messages. (<https://github.com/matrix-org/matrix-doc/issues/2043>)
- [x] Use consistent examples of events throughout the specification. (<https://github.com/matrix-org/matrix-doc/issues/2051>)
- [x] Clarify which push rule condition kinds exist. (<https://github.com/matrix-org/matrix-doc/issues/2052>)
- [x] Clarify the required fields on `m.file` (and similar) messages. (<https://github.com/matrix-org/matrix-doc/issues/2053>)
- [x] Clarify which parameters apply in what scenarios on `/register`. (<https://github.com/matrix-org/matrix-doc/issues/2055>)
- [x] Clarify how to interpret changes of `membership` over time. (<https://github.com/matrix-org/matrix-doc/issues/2056>)
- [x] Clarify exactly what invite_room_state consists of. (<https://github.com/matrix-org/matrix-doc/issues/2067>)
- [x] Clarify how the content repository works, and what it is used for. (<https://github.com/matrix-org/matrix-doc/issues/2068>)
- [x] Clarify the order events in chunk are returned in for `/messages`. (<https://github.com/matrix-org/matrix-doc/issues/2069>)
- [x] Clarify the key object definition for the key management API. (<https://github.com/matrix-org/matrix-doc/issues/2083>)
- [x] Reorganize information about events into a common section. (<https://github.com/matrix-org/matrix-doc/issues/2087>)
- [ ] De-duplicate `/state/<event_type>` endpoints, clarifying that the `<state_key>` is optional. (<https://github.com/matrix-org/matrix-doc/issues/2088>)
- [x] Clarify when and where CORS headers should be returned. (<https://github.com/matrix-org/matrix-doc/issues/2089>)
- [x] Clarify when authorization and rate-limiting are not applicable. (<https://github.com/matrix-org/matrix-doc/issues/2090>)
- [x] Clarify that `/register` must produce valid Matrix User IDs. (<https://github.com/matrix-org/matrix-doc/issues/2091>)
- [x] Clarify how `unread_notifications` is calculated. (<https://github.com/matrix-org/matrix-doc/issues/2097>)
- [x] Clarify what a "module" is and update feature profiles for clients. (<https://github.com/matrix-org/matrix-doc/issues/2098>)

**Comment by iinuwa** [comment]
> [] Fix various spelling mistakes throughout the specification. (matrix-org/matrix-doc#1838...

The only change to field types is a typo in the E2E module (matrix-org/matrix-doc@1a739ec), which this API doesn't support yet right? If not, I think that can be checked off.

**Comment by jplatte** [comment]
Since we've got our own independent doc texts anyway, I'll remove that entry (and any other I find that are simply fixing typos).

**Comment by iinuwa** [comment]
Would it be helpful if I went through all the change log tracking issues and created individual GitHub issues for items we haven't implemented?

**Comment by jplatte** [comment]
Maybe not for the spec clarifications, since many of them affect only docs that we don't have in ruma-client-api anyways, but sure, go ahead.

**Comment by iinuwa** [comment]
All right, went through all of these but one. Do we support optional [trailing] path parameters? If so, I think we can drop a couple of endpoints that are semantically identical. Otherwise, we can check it off and close this issue.

**Comment by jplatte** [comment]
Supporting those would be very hard, since we want to be able to integrate with multiple web frameworks in addition to clients. It seems like a bad idea to require all of the ones we're going to support to have a notion of optional trailing path parameters. I think it makes sense to keep those endpoints split for now, even if they might not semantically be much different.
